### ISSUE TITLE
nullpointexception 

### ISSUE THREAD

**Issue by serkandyck** [jariz/MaterialUp#15]
java.lang.NullPointerException
            at io.jari.materialup.utils.ParseUtils.parseItems(ParseUtils.java:44)
            at io.jari.materialup.connection.UpRequests$1.onResponse(UpRequests.java:47)
            at io.jari.materialup.connection.UpRequests$1.onResponse(UpRequests.java:44)

**Comment by jariz** [comment]
Yes, we're very much aware of this. We're currently implementing the official MU API and getting rid of all html parsing.
Also, once again, this project isn't done yet, if you want to join in on development, message me (username jari) on the MU slack.
